// @ts-nocheck

/**
 * Auto Generated by orval
 * Do not edit manually.
 * BaseApp Backend API
 * API para el sistema de BaseApp Backend
 */

import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type {
  ApiShowsSearchRetrieveParams,
  EmailTokenObtain,
  MovieDetail,
  PatchedUser,
  TokenRefresh,
  TrendingShowsResponse,
  TvDetail,
  User,
  UserRegistration,
} from "../baseAppBackendAPI.schemas";
import { customAxios } from "../../lib/axiosInstance";

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> =
  (<T>() => T extends X ? 1 : 2) extends <T>() => T extends Y ? 1 : 2 ? A : B;

type WritableKeys<T> = {
  [P in keyof T]-?: IfEquals<
    { [Q in P]: T[P] },
    { -readonly [Q in P]: T[P] },
    P
  >;
}[keyof T];

type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (
  k: infer I,
) => void
  ? I
  : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>]
  ? {
      [P in keyof Writable<T>]: T[P] extends object
        ? NonReadonly<NonNullable<T[P]>>
        : T[P];
    }
  : DistributeReadOnlyOverUnions<T>;

/**
 * Takes a set of user credentials and returns an access and refresh JSON web
token pair to prove the authentication of those credentials.
 */
export const apiAuthLoginCreate = (
  emailTokenObtain: EmailTokenObtain,
  signal?: AbortSignal,
) => {
  return customAxios<EmailTokenObtain>({
    url: `/api/auth/login/`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: emailTokenObtain,
    signal,
  });
};

export const getApiAuthLoginCreateMutationOptions = <
  TData = Awaited<ReturnType<typeof apiAuthLoginCreate>>,
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    TData,
    TError,
    { data: EmailTokenObtain },
    TContext
  >;
}) => {
  const mutationKey = ["apiAuthLoginCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiAuthLoginCreate>>,
    { data: EmailTokenObtain }
  > = (props) => {
    const { data } = props ?? {};

    return apiAuthLoginCreate(data);
  };

  return { mutationFn, ...mutationOptions } as UseMutationOptions<
    TData,
    TError,
    { data: EmailTokenObtain },
    TContext
  >;
};

export type ApiAuthLoginCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof apiAuthLoginCreate>>
>;
export type ApiAuthLoginCreateMutationBody = EmailTokenObtain;
export type ApiAuthLoginCreateMutationError = unknown;

export const useApiAuthLoginCreate = <
  TData = Awaited<ReturnType<typeof apiAuthLoginCreate>>,
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    TData,
    TError,
    { data: EmailTokenObtain },
    TContext
  >;
}): UseMutationResult<TData, TError, { data: EmailTokenObtain }, TContext> => {
  const mutationOptions = getApiAuthLoginCreateMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * Takes a refresh type JSON web token and returns an access type JSON web
token if the refresh token is valid.
 */
export const apiAuthRefreshCreate = (
  tokenRefresh: NonReadonly<TokenRefresh>,
  signal?: AbortSignal,
) => {
  return customAxios<TokenRefresh>({
    url: `/api/auth/refresh/`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: tokenRefresh,
    signal,
  });
};

export const getApiAuthRefreshCreateMutationOptions = <
  TData = Awaited<ReturnType<typeof apiAuthRefreshCreate>>,
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    TData,
    TError,
    { data: NonReadonly<TokenRefresh> },
    TContext
  >;
}) => {
  const mutationKey = ["apiAuthRefreshCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiAuthRefreshCreate>>,
    { data: NonReadonly<TokenRefresh> }
  > = (props) => {
    const { data } = props ?? {};

    return apiAuthRefreshCreate(data);
  };

  return { mutationFn, ...mutationOptions } as UseMutationOptions<
    TData,
    TError,
    { data: NonReadonly<TokenRefresh> },
    TContext
  >;
};

export type ApiAuthRefreshCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof apiAuthRefreshCreate>>
>;
export type ApiAuthRefreshCreateMutationBody = NonReadonly<TokenRefresh>;
export type ApiAuthRefreshCreateMutationError = unknown;

export const useApiAuthRefreshCreate = <
  TData = Awaited<ReturnType<typeof apiAuthRefreshCreate>>,
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    TData,
    TError,
    { data: NonReadonly<TokenRefresh> },
    TContext
  >;
}): UseMutationResult<
  TData,
  TError,
  { data: NonReadonly<TokenRefresh> },
  TContext
> => {
  const mutationOptions = getApiAuthRefreshCreateMutationOptions(options);

  return useMutation(mutationOptions);
};
export const apiAuthRegisterCreate = (
  userRegistration: UserRegistration,
  signal?: AbortSignal,
) => {
  return customAxios<UserRegistration>({
    url: `/api/auth/register/`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: userRegistration,
    signal,
  });
};

export const getApiAuthRegisterCreateMutationOptions = <
  TData = Awaited<ReturnType<typeof apiAuthRegisterCreate>>,
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    TData,
    TError,
    { data: UserRegistration },
    TContext
  >;
}) => {
  const mutationKey = ["apiAuthRegisterCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiAuthRegisterCreate>>,
    { data: UserRegistration }
  > = (props) => {
    const { data } = props ?? {};

    return apiAuthRegisterCreate(data);
  };

  return { mutationFn, ...mutationOptions } as UseMutationOptions<
    TData,
    TError,
    { data: UserRegistration },
    TContext
  >;
};

export type ApiAuthRegisterCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof apiAuthRegisterCreate>>
>;
export type ApiAuthRegisterCreateMutationBody = UserRegistration;
export type ApiAuthRegisterCreateMutationError = unknown;

export const useApiAuthRegisterCreate = <
  TData = Awaited<ReturnType<typeof apiAuthRegisterCreate>>,
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    TData,
    TError,
    { data: UserRegistration },
    TContext
  >;
}): UseMutationResult<TData, TError, { data: UserRegistration }, TContext> => {
  const mutationOptions = getApiAuthRegisterCreateMutationOptions(options);

  return useMutation(mutationOptions);
};
export const apiShowsRetrieve = (signal?: AbortSignal) => {
  return customAxios<void>({ url: `/api/shows/`, method: "GET", signal });
};

export const getApiShowsRetrieveQueryKey = () => {
  return [`/api/shows/`] as const;
};

export const getApiShowsRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof apiShowsRetrieve>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof apiShowsRetrieve>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getApiShowsRetrieveQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof apiShowsRetrieve>>
  > = ({ signal }) => apiShowsRetrieve(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof apiShowsRetrieve>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type ApiShowsRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof apiShowsRetrieve>>
>;
export type ApiShowsRetrieveQueryError = unknown;

export function useApiShowsRetrieve<
  TData = Awaited<ReturnType<typeof apiShowsRetrieve>>,
  TError = unknown,
>(options: {
  query: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof apiShowsRetrieve>>, TError, TData>
  > &
    Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof apiShowsRetrieve>>,
        TError,
        TData
      >,
      "initialData"
    >;
}): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useApiShowsRetrieve<
  TData = Awaited<ReturnType<typeof apiShowsRetrieve>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof apiShowsRetrieve>>, TError, TData>
  > &
    Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof apiShowsRetrieve>>,
        TError,
        TData
      >,
      "initialData"
    >;
}): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useApiShowsRetrieve<
  TData = Awaited<ReturnType<typeof apiShowsRetrieve>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof apiShowsRetrieve>>, TError, TData>
  >;
}): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

export function useApiShowsRetrieve<
  TData = Awaited<ReturnType<typeof apiShowsRetrieve>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof apiShowsRetrieve>>, TError, TData>
  >;
}): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getApiShowsRetrieveQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const apiShowsCreate = (signal?: AbortSignal) => {
  return customAxios<void>({ url: `/api/shows/`, method: "POST", signal });
};

export const getApiShowsCreateMutationOptions = <
  TData = Awaited<ReturnType<typeof apiShowsCreate>>,
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<TData, TError, void, TContext>;
}) => {
  const mutationKey = ["apiShowsCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiShowsCreate>>,
    void
  > = () => {
    return apiShowsCreate();
  };

  return { mutationFn, ...mutationOptions } as UseMutationOptions<
    TData,
    TError,
    void,
    TContext
  >;
};

export type ApiShowsCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof apiShowsCreate>>
>;

export type ApiShowsCreateMutationError = unknown;

export const useApiShowsCreate = <
  TData = Awaited<ReturnType<typeof apiShowsCreate>>,
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<TData, TError, void, TContext>;
}): UseMutationResult<TData, TError, void, TContext> => {
  const mutationOptions = getApiShowsCreateMutationOptions(options);

  return useMutation(mutationOptions);
};
export const apiShowsRetrieve2 = (id: string, signal?: AbortSignal) => {
  return customAxios<void>({ url: `/api/shows/${id}/`, method: "GET", signal });
};

export const getApiShowsRetrieve2QueryKey = (id: string) => {
  return [`/api/shows/${id}/`] as const;
};

export const getApiShowsRetrieve2QueryOptions = <
  TData = Awaited<ReturnType<typeof apiShowsRetrieve2>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiShowsRetrieve2>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getApiShowsRetrieve2QueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof apiShowsRetrieve2>>
  > = ({ signal }) => apiShowsRetrieve2(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof apiShowsRetrieve2>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type ApiShowsRetrieve2QueryResult = NonNullable<
  Awaited<ReturnType<typeof apiShowsRetrieve2>>
>;
export type ApiShowsRetrieve2QueryError = unknown;

export function useApiShowsRetrieve2<
  TData = Awaited<ReturnType<typeof apiShowsRetrieve2>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiShowsRetrieve2>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof apiShowsRetrieve2>>,
          TError,
          TData
        >,
        "initialData"
      >;
  },
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useApiShowsRetrieve2<
  TData = Awaited<ReturnType<typeof apiShowsRetrieve2>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiShowsRetrieve2>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof apiShowsRetrieve2>>,
          TError,
          TData
        >,
        "initialData"
      >;
  },
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useApiShowsRetrieve2<
  TData = Awaited<ReturnType<typeof apiShowsRetrieve2>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiShowsRetrieve2>>,
        TError,
        TData
      >
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

export function useApiShowsRetrieve2<
  TData = Awaited<ReturnType<typeof apiShowsRetrieve2>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiShowsRetrieve2>>,
        TError,
        TData
      >
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getApiShowsRetrieve2QueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const apiShowsUpdate = (id: string) => {
  return customAxios<void>({ url: `/api/shows/${id}/`, method: "PUT" });
};

export const getApiShowsUpdateMutationOptions = <
  TData = Awaited<ReturnType<typeof apiShowsUpdate>>,
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<TData, TError, { id: string }, TContext>;
}) => {
  const mutationKey = ["apiShowsUpdate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiShowsUpdate>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return apiShowsUpdate(id);
  };

  return { mutationFn, ...mutationOptions } as UseMutationOptions<
    TData,
    TError,
    { id: string },
    TContext
  >;
};

export type ApiShowsUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof apiShowsUpdate>>
>;

export type ApiShowsUpdateMutationError = unknown;

export const useApiShowsUpdate = <
  TData = Awaited<ReturnType<typeof apiShowsUpdate>>,
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<TData, TError, { id: string }, TContext>;
}): UseMutationResult<TData, TError, { id: string }, TContext> => {
  const mutationOptions = getApiShowsUpdateMutationOptions(options);

  return useMutation(mutationOptions);
};
export const apiShowsPartialUpdate = (id: string) => {
  return customAxios<void>({ url: `/api/shows/${id}/`, method: "PATCH" });
};

export const getApiShowsPartialUpdateMutationOptions = <
  TData = Awaited<ReturnType<typeof apiShowsPartialUpdate>>,
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<TData, TError, { id: string }, TContext>;
}) => {
  const mutationKey = ["apiShowsPartialUpdate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiShowsPartialUpdate>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return apiShowsPartialUpdate(id);
  };

  return { mutationFn, ...mutationOptions } as UseMutationOptions<
    TData,
    TError,
    { id: string },
    TContext
  >;
};

export type ApiShowsPartialUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof apiShowsPartialUpdate>>
>;

export type ApiShowsPartialUpdateMutationError = unknown;

export const useApiShowsPartialUpdate = <
  TData = Awaited<ReturnType<typeof apiShowsPartialUpdate>>,
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<TData, TError, { id: string }, TContext>;
}): UseMutationResult<TData, TError, { id: string }, TContext> => {
  const mutationOptions = getApiShowsPartialUpdateMutationOptions(options);

  return useMutation(mutationOptions);
};
export const apiShowsDestroy = (id: string) => {
  return customAxios<void>({ url: `/api/shows/${id}/`, method: "DELETE" });
};

export const getApiShowsDestroyMutationOptions = <
  TData = Awaited<ReturnType<typeof apiShowsDestroy>>,
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<TData, TError, { id: string }, TContext>;
}) => {
  const mutationKey = ["apiShowsDestroy"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiShowsDestroy>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return apiShowsDestroy(id);
  };

  return { mutationFn, ...mutationOptions } as UseMutationOptions<
    TData,
    TError,
    { id: string },
    TContext
  >;
};

export type ApiShowsDestroyMutationResult = NonNullable<
  Awaited<ReturnType<typeof apiShowsDestroy>>
>;

export type ApiShowsDestroyMutationError = unknown;

export const useApiShowsDestroy = <
  TData = Awaited<ReturnType<typeof apiShowsDestroy>>,
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<TData, TError, { id: string }, TContext>;
}): UseMutationResult<TData, TError, { id: string }, TContext> => {
  const mutationOptions = getApiShowsDestroyMutationOptions(options);

  return useMutation(mutationOptions);
};
export const apiShowsMovieRetrieve = (id: string, signal?: AbortSignal) => {
  return customAxios<MovieDetail>({
    url: `/api/shows/movie/${id}/`,
    method: "GET",
    signal,
  });
};

export const getApiShowsMovieRetrieveQueryKey = (id: string) => {
  return [`/api/shows/movie/${id}/`] as const;
};

export const getApiShowsMovieRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof apiShowsMovieRetrieve>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiShowsMovieRetrieve>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getApiShowsMovieRetrieveQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof apiShowsMovieRetrieve>>
  > = ({ signal }) => apiShowsMovieRetrieve(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof apiShowsMovieRetrieve>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type ApiShowsMovieRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof apiShowsMovieRetrieve>>
>;
export type ApiShowsMovieRetrieveQueryError = unknown;

export function useApiShowsMovieRetrieve<
  TData = Awaited<ReturnType<typeof apiShowsMovieRetrieve>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiShowsMovieRetrieve>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof apiShowsMovieRetrieve>>,
          TError,
          TData
        >,
        "initialData"
      >;
  },
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useApiShowsMovieRetrieve<
  TData = Awaited<ReturnType<typeof apiShowsMovieRetrieve>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiShowsMovieRetrieve>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof apiShowsMovieRetrieve>>,
          TError,
          TData
        >,
        "initialData"
      >;
  },
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useApiShowsMovieRetrieve<
  TData = Awaited<ReturnType<typeof apiShowsMovieRetrieve>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiShowsMovieRetrieve>>,
        TError,
        TData
      >
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

export function useApiShowsMovieRetrieve<
  TData = Awaited<ReturnType<typeof apiShowsMovieRetrieve>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiShowsMovieRetrieve>>,
        TError,
        TData
      >
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getApiShowsMovieRetrieveQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const apiShowsSearchRetrieve = (
  params: ApiShowsSearchRetrieveParams,
  signal?: AbortSignal,
) => {
  return customAxios<TrendingShowsResponse>({
    url: `/api/shows/search/`,
    method: "GET",
    params,
    signal,
  });
};

export const getApiShowsSearchRetrieveQueryKey = (
  params: ApiShowsSearchRetrieveParams,
) => {
  return [`/api/shows/search/`, ...(params ? [params] : [])] as const;
};

export const getApiShowsSearchRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof apiShowsSearchRetrieve>>,
  TError = unknown,
>(
  params: ApiShowsSearchRetrieveParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiShowsSearchRetrieve>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getApiShowsSearchRetrieveQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof apiShowsSearchRetrieve>>
  > = ({ signal }) => apiShowsSearchRetrieve(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof apiShowsSearchRetrieve>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type ApiShowsSearchRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof apiShowsSearchRetrieve>>
>;
export type ApiShowsSearchRetrieveQueryError = unknown;

export function useApiShowsSearchRetrieve<
  TData = Awaited<ReturnType<typeof apiShowsSearchRetrieve>>,
  TError = unknown,
>(
  params: ApiShowsSearchRetrieveParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiShowsSearchRetrieve>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof apiShowsSearchRetrieve>>,
          TError,
          TData
        >,
        "initialData"
      >;
  },
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useApiShowsSearchRetrieve<
  TData = Awaited<ReturnType<typeof apiShowsSearchRetrieve>>,
  TError = unknown,
>(
  params: ApiShowsSearchRetrieveParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiShowsSearchRetrieve>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof apiShowsSearchRetrieve>>,
          TError,
          TData
        >,
        "initialData"
      >;
  },
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useApiShowsSearchRetrieve<
  TData = Awaited<ReturnType<typeof apiShowsSearchRetrieve>>,
  TError = unknown,
>(
  params: ApiShowsSearchRetrieveParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiShowsSearchRetrieve>>,
        TError,
        TData
      >
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

export function useApiShowsSearchRetrieve<
  TData = Awaited<ReturnType<typeof apiShowsSearchRetrieve>>,
  TError = unknown,
>(
  params: ApiShowsSearchRetrieveParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiShowsSearchRetrieve>>,
        TError,
        TData
      >
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getApiShowsSearchRetrieveQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const apiShowsTrendingRetrieve = (signal?: AbortSignal) => {
  return customAxios<TrendingShowsResponse>({
    url: `/api/shows/trending/`,
    method: "GET",
    signal,
  });
};

export const getApiShowsTrendingRetrieveQueryKey = () => {
  return [`/api/shows/trending/`] as const;
};

export const getApiShowsTrendingRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof apiShowsTrendingRetrieve>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof apiShowsTrendingRetrieve>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getApiShowsTrendingRetrieveQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof apiShowsTrendingRetrieve>>
  > = ({ signal }) => apiShowsTrendingRetrieve(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof apiShowsTrendingRetrieve>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type ApiShowsTrendingRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof apiShowsTrendingRetrieve>>
>;
export type ApiShowsTrendingRetrieveQueryError = unknown;

export function useApiShowsTrendingRetrieve<
  TData = Awaited<ReturnType<typeof apiShowsTrendingRetrieve>>,
  TError = unknown,
>(options: {
  query: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof apiShowsTrendingRetrieve>>,
      TError,
      TData
    >
  > &
    Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof apiShowsTrendingRetrieve>>,
        TError,
        TData
      >,
      "initialData"
    >;
}): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useApiShowsTrendingRetrieve<
  TData = Awaited<ReturnType<typeof apiShowsTrendingRetrieve>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof apiShowsTrendingRetrieve>>,
      TError,
      TData
    >
  > &
    Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof apiShowsTrendingRetrieve>>,
        TError,
        TData
      >,
      "initialData"
    >;
}): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useApiShowsTrendingRetrieve<
  TData = Awaited<ReturnType<typeof apiShowsTrendingRetrieve>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof apiShowsTrendingRetrieve>>,
      TError,
      TData
    >
  >;
}): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

export function useApiShowsTrendingRetrieve<
  TData = Awaited<ReturnType<typeof apiShowsTrendingRetrieve>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof apiShowsTrendingRetrieve>>,
      TError,
      TData
    >
  >;
}): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getApiShowsTrendingRetrieveQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const apiShowsTvRetrieve = (id: string, signal?: AbortSignal) => {
  return customAxios<TvDetail>({
    url: `/api/shows/tv/${id}/`,
    method: "GET",
    signal,
  });
};

export const getApiShowsTvRetrieveQueryKey = (id: string) => {
  return [`/api/shows/tv/${id}/`] as const;
};

export const getApiShowsTvRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof apiShowsTvRetrieve>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiShowsTvRetrieve>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getApiShowsTvRetrieveQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof apiShowsTvRetrieve>>
  > = ({ signal }) => apiShowsTvRetrieve(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof apiShowsTvRetrieve>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type ApiShowsTvRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof apiShowsTvRetrieve>>
>;
export type ApiShowsTvRetrieveQueryError = unknown;

export function useApiShowsTvRetrieve<
  TData = Awaited<ReturnType<typeof apiShowsTvRetrieve>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiShowsTvRetrieve>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof apiShowsTvRetrieve>>,
          TError,
          TData
        >,
        "initialData"
      >;
  },
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useApiShowsTvRetrieve<
  TData = Awaited<ReturnType<typeof apiShowsTvRetrieve>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiShowsTvRetrieve>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof apiShowsTvRetrieve>>,
          TError,
          TData
        >,
        "initialData"
      >;
  },
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useApiShowsTvRetrieve<
  TData = Awaited<ReturnType<typeof apiShowsTvRetrieve>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiShowsTvRetrieve>>,
        TError,
        TData
      >
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

export function useApiShowsTvRetrieve<
  TData = Awaited<ReturnType<typeof apiShowsTvRetrieve>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiShowsTvRetrieve>>,
        TError,
        TData
      >
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getApiShowsTvRetrieveQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const apiUsersList = (signal?: AbortSignal) => {
  return customAxios<User[]>({ url: `/api/users/`, method: "GET", signal });
};

export const getApiUsersListQueryKey = () => {
  return [`/api/users/`] as const;
};

export const getApiUsersListQueryOptions = <
  TData = Awaited<ReturnType<typeof apiUsersList>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof apiUsersList>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getApiUsersListQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof apiUsersList>>> = ({
    signal,
  }) => apiUsersList(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof apiUsersList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type ApiUsersListQueryResult = NonNullable<
  Awaited<ReturnType<typeof apiUsersList>>
>;
export type ApiUsersListQueryError = unknown;

export function useApiUsersList<
  TData = Awaited<ReturnType<typeof apiUsersList>>,
  TError = unknown,
>(options: {
  query: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof apiUsersList>>, TError, TData>
  > &
    Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof apiUsersList>>,
        TError,
        TData
      >,
      "initialData"
    >;
}): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useApiUsersList<
  TData = Awaited<ReturnType<typeof apiUsersList>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof apiUsersList>>, TError, TData>
  > &
    Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof apiUsersList>>,
        TError,
        TData
      >,
      "initialData"
    >;
}): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useApiUsersList<
  TData = Awaited<ReturnType<typeof apiUsersList>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof apiUsersList>>, TError, TData>
  >;
}): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

export function useApiUsersList<
  TData = Awaited<ReturnType<typeof apiUsersList>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof apiUsersList>>, TError, TData>
  >;
}): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getApiUsersListQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const apiUsersCreate = (
  user: NonReadonly<User>,
  signal?: AbortSignal,
) => {
  return customAxios<User>({
    url: `/api/users/`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: user,
    signal,
  });
};

export const getApiUsersCreateMutationOptions = <
  TData = Awaited<ReturnType<typeof apiUsersCreate>>,
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    TData,
    TError,
    { data: NonReadonly<User> },
    TContext
  >;
}) => {
  const mutationKey = ["apiUsersCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiUsersCreate>>,
    { data: NonReadonly<User> }
  > = (props) => {
    const { data } = props ?? {};

    return apiUsersCreate(data);
  };

  return { mutationFn, ...mutationOptions } as UseMutationOptions<
    TData,
    TError,
    { data: NonReadonly<User> },
    TContext
  >;
};

export type ApiUsersCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof apiUsersCreate>>
>;
export type ApiUsersCreateMutationBody = NonReadonly<User>;
export type ApiUsersCreateMutationError = unknown;

export const useApiUsersCreate = <
  TData = Awaited<ReturnType<typeof apiUsersCreate>>,
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    TData,
    TError,
    { data: NonReadonly<User> },
    TContext
  >;
}): UseMutationResult<TData, TError, { data: NonReadonly<User> }, TContext> => {
  const mutationOptions = getApiUsersCreateMutationOptions(options);

  return useMutation(mutationOptions);
};
export const apiUsersRetrieve = (id: number, signal?: AbortSignal) => {
  return customAxios<User>({ url: `/api/users/${id}/`, method: "GET", signal });
};

export const getApiUsersRetrieveQueryKey = (id: number) => {
  return [`/api/users/${id}/`] as const;
};

export const getApiUsersRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof apiUsersRetrieve>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiUsersRetrieve>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getApiUsersRetrieveQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof apiUsersRetrieve>>
  > = ({ signal }) => apiUsersRetrieve(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof apiUsersRetrieve>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type ApiUsersRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof apiUsersRetrieve>>
>;
export type ApiUsersRetrieveQueryError = unknown;

export function useApiUsersRetrieve<
  TData = Awaited<ReturnType<typeof apiUsersRetrieve>>,
  TError = unknown,
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiUsersRetrieve>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof apiUsersRetrieve>>,
          TError,
          TData
        >,
        "initialData"
      >;
  },
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useApiUsersRetrieve<
  TData = Awaited<ReturnType<typeof apiUsersRetrieve>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiUsersRetrieve>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof apiUsersRetrieve>>,
          TError,
          TData
        >,
        "initialData"
      >;
  },
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useApiUsersRetrieve<
  TData = Awaited<ReturnType<typeof apiUsersRetrieve>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiUsersRetrieve>>,
        TError,
        TData
      >
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

export function useApiUsersRetrieve<
  TData = Awaited<ReturnType<typeof apiUsersRetrieve>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiUsersRetrieve>>,
        TError,
        TData
      >
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getApiUsersRetrieveQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const apiUsersUpdate = (id: number, user: NonReadonly<User>) => {
  return customAxios<User>({
    url: `/api/users/${id}/`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: user,
  });
};

export const getApiUsersUpdateMutationOptions = <
  TData = Awaited<ReturnType<typeof apiUsersUpdate>>,
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    TData,
    TError,
    { id: number; data: NonReadonly<User> },
    TContext
  >;
}) => {
  const mutationKey = ["apiUsersUpdate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiUsersUpdate>>,
    { id: number; data: NonReadonly<User> }
  > = (props) => {
    const { id, data } = props ?? {};

    return apiUsersUpdate(id, data);
  };

  return { mutationFn, ...mutationOptions } as UseMutationOptions<
    TData,
    TError,
    { id: number; data: NonReadonly<User> },
    TContext
  >;
};

export type ApiUsersUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof apiUsersUpdate>>
>;
export type ApiUsersUpdateMutationBody = NonReadonly<User>;
export type ApiUsersUpdateMutationError = unknown;

export const useApiUsersUpdate = <
  TData = Awaited<ReturnType<typeof apiUsersUpdate>>,
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    TData,
    TError,
    { id: number; data: NonReadonly<User> },
    TContext
  >;
}): UseMutationResult<
  TData,
  TError,
  { id: number; data: NonReadonly<User> },
  TContext
> => {
  const mutationOptions = getApiUsersUpdateMutationOptions(options);

  return useMutation(mutationOptions);
};
export const apiUsersPartialUpdate = (
  id: number,
  patchedUser: NonReadonly<PatchedUser>,
) => {
  return customAxios<User>({
    url: `/api/users/${id}/`,
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    data: patchedUser,
  });
};

export const getApiUsersPartialUpdateMutationOptions = <
  TData = Awaited<ReturnType<typeof apiUsersPartialUpdate>>,
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    TData,
    TError,
    { id: number; data: NonReadonly<PatchedUser> },
    TContext
  >;
}) => {
  const mutationKey = ["apiUsersPartialUpdate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiUsersPartialUpdate>>,
    { id: number; data: NonReadonly<PatchedUser> }
  > = (props) => {
    const { id, data } = props ?? {};

    return apiUsersPartialUpdate(id, data);
  };

  return { mutationFn, ...mutationOptions } as UseMutationOptions<
    TData,
    TError,
    { id: number; data: NonReadonly<PatchedUser> },
    TContext
  >;
};

export type ApiUsersPartialUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof apiUsersPartialUpdate>>
>;
export type ApiUsersPartialUpdateMutationBody = NonReadonly<PatchedUser>;
export type ApiUsersPartialUpdateMutationError = unknown;

export const useApiUsersPartialUpdate = <
  TData = Awaited<ReturnType<typeof apiUsersPartialUpdate>>,
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    TData,
    TError,
    { id: number; data: NonReadonly<PatchedUser> },
    TContext
  >;
}): UseMutationResult<
  TData,
  TError,
  { id: number; data: NonReadonly<PatchedUser> },
  TContext
> => {
  const mutationOptions = getApiUsersPartialUpdateMutationOptions(options);

  return useMutation(mutationOptions);
};
export const apiUsersDestroy = (id: number) => {
  return customAxios<void>({ url: `/api/users/${id}/`, method: "DELETE" });
};

export const getApiUsersDestroyMutationOptions = <
  TData = Awaited<ReturnType<typeof apiUsersDestroy>>,
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<TData, TError, { id: number }, TContext>;
}) => {
  const mutationKey = ["apiUsersDestroy"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiUsersDestroy>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return apiUsersDestroy(id);
  };

  return { mutationFn, ...mutationOptions } as UseMutationOptions<
    TData,
    TError,
    { id: number },
    TContext
  >;
};

export type ApiUsersDestroyMutationResult = NonNullable<
  Awaited<ReturnType<typeof apiUsersDestroy>>
>;

export type ApiUsersDestroyMutationError = unknown;

export const useApiUsersDestroy = <
  TData = Awaited<ReturnType<typeof apiUsersDestroy>>,
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<TData, TError, { id: number }, TContext>;
}): UseMutationResult<TData, TError, { id: number }, TContext> => {
  const mutationOptions = getApiUsersDestroyMutationOptions(options);

  return useMutation(mutationOptions);
};
export const apiUsersMeRetrieve = (signal?: AbortSignal) => {
  return customAxios<User>({ url: `/api/users/me/`, method: "GET", signal });
};

export const getApiUsersMeRetrieveQueryKey = () => {
  return [`/api/users/me/`] as const;
};

export const getApiUsersMeRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof apiUsersMeRetrieve>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof apiUsersMeRetrieve>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getApiUsersMeRetrieveQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof apiUsersMeRetrieve>>
  > = ({ signal }) => apiUsersMeRetrieve(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof apiUsersMeRetrieve>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type ApiUsersMeRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof apiUsersMeRetrieve>>
>;
export type ApiUsersMeRetrieveQueryError = unknown;

export function useApiUsersMeRetrieve<
  TData = Awaited<ReturnType<typeof apiUsersMeRetrieve>>,
  TError = unknown,
>(options: {
  query: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof apiUsersMeRetrieve>>,
      TError,
      TData
    >
  > &
    Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof apiUsersMeRetrieve>>,
        TError,
        TData
      >,
      "initialData"
    >;
}): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useApiUsersMeRetrieve<
  TData = Awaited<ReturnType<typeof apiUsersMeRetrieve>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof apiUsersMeRetrieve>>,
      TError,
      TData
    >
  > &
    Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof apiUsersMeRetrieve>>,
        TError,
        TData
      >,
      "initialData"
    >;
}): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useApiUsersMeRetrieve<
  TData = Awaited<ReturnType<typeof apiUsersMeRetrieve>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof apiUsersMeRetrieve>>,
      TError,
      TData
    >
  >;
}): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

export function useApiUsersMeRetrieve<
  TData = Awaited<ReturnType<typeof apiUsersMeRetrieve>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof apiUsersMeRetrieve>>,
      TError,
      TData
    >
  >;
}): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getApiUsersMeRetrieveQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
