// @ts-nocheck

/**
 * Auto Generated by orval
 * Do not edit manually.
 * BaseApp Backend API
 * API para el sistema de BaseApp Backend
 */

export enum ApiShowsTrendingRetrieveTimeWindow {
  day = "day",
  week = "week",
}
export type ApiShowsTrendingRetrieveParams = {
  /**
   * Time window
   */
  time_window?: ApiShowsTrendingRetrieveTimeWindow;
};

export type ApiShowsSearchRetrieveParams = {
  /**
   * Query string
   */
  query: string;
};

export enum ApiShowsPopularRetrieveMediaType {
  movie = "movie",
  tv = "tv",
}
export type ApiShowsPopularRetrieveParams = {
  /**
   * Media type
   */
  media_type?: ApiShowsPopularRetrieveMediaType;
};

export type ApiShowsGetTvEpisodesRetrieveParams = {
  /**
   * Season number
   */
  season_number: number;
  /**
   * TV ID
   */
  tv_id: number;
};

export interface UserRegistration {
  /**
   * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
   * @maxLength 150
   * @pattern ^[\w.@+-]+$
   */
  username: string;
  /** @maxLength 254 */
  email?: string;
  password: string;
}

export interface User {
  readonly id: number;
  /**
   * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
   * @maxLength 150
   * @pattern ^[\w.@+-]+$
   */
  username: string;
  /** @maxLength 254 */
  email?: string;
}

export interface TvProgress {
  readonly id: number;
  /**
   * @minimum -9223372036854776000
   * @maximum 9223372036854776000
   */
  season?: number;
  /**
   * @minimum -9223372036854776000
   * @maximum 9223372036854776000
   */
  episode?: number;
  watched_seconds?: number;
  total_seconds?: number;
}

export interface TvEpisodesResponse {
  _id: string;
  air_date: string;
  episodes: TvEpisode[];
  name: string;
  overview: string;
  id: number;
  /** @nullable */
  poster_path: string | null;
  season_number: number;
  vote_average: number;
}

export type TvEpisodeGuestStarsItem = { [key: string]: unknown };

export type TvEpisodeCrewItem = { [key: string]: unknown };

export interface TvEpisode {
  air_date: string;
  episode_number: number;
  id: number;
  name: string;
  overview: string;
  production_code: string;
  runtime: number;
  season_number: number;
  show_id: number;
  /** @nullable */
  still_path: string | null;
  vote_average: number;
  vote_count: number;
  crew: TvEpisodeCrewItem[];
  guest_stars: TvEpisodeGuestStarsItem[];
}

export type TvDetailSpokenLanguagesItem = { [key: string]: unknown };

export type TvDetailSeasonsItem = { [key: string]: unknown };

export type TvDetailProductionCountriesItem = { [key: string]: unknown };

export type TvDetailProductionCompaniesItem = { [key: string]: unknown };

export type TvDetailNetworksItem = { [key: string]: unknown };

/**
 * @nullable
 */
export type TvDetailNextEpisodeToAir = { [key: string]: unknown } | null;

/**
 * @nullable
 */
export type TvDetailLastEpisodeToAir = { [key: string]: unknown } | null;

export type TvDetailCreatedByItem = { [key: string]: unknown };

export interface TvDetail {
  adult: boolean;
  /** @nullable */
  backdrop_path: string | null;
  created_by: TvDetailCreatedByItem[];
  episode_run_time: number[];
  first_air_date: string;
  genres: Genre[];
  /** @nullable */
  homepage: string | null;
  id: number;
  in_production: boolean;
  languages: string[];
  last_air_date: string;
  /** @nullable */
  last_episode_to_air: TvDetailLastEpisodeToAir;
  name: string;
  /** @nullable */
  next_episode_to_air: TvDetailNextEpisodeToAir;
  networks: TvDetailNetworksItem[];
  number_of_episodes: number;
  number_of_seasons: number;
  origin_country: string[];
  original_language: string;
  original_name: string;
  overview: string;
  popularity: number;
  /** @nullable */
  poster_path: string | null;
  production_companies: TvDetailProductionCompaniesItem[];
  production_countries: TvDetailProductionCountriesItem[];
  seasons: TvDetailSeasonsItem[];
  spoken_languages: TvDetailSpokenLanguagesItem[];
  status: string;
  tagline: string;
  type: string;
  vote_average: number;
  vote_count: number;
}

export interface TrendingShow {
  id: number;
  /** @nullable */
  backdrop_path: string | null;
  /** @nullable */
  poster_path: string | null;
  overview: string;
  media_type: MediaTypeEnum;
  adult: boolean;
  original_language: string;
  genre_ids: number[];
  popularity: number;
  vote_average: number;
  vote_count: number;
  title?: string;
  original_title?: string;
  release_date?: string;
  video?: boolean;
  name?: string;
  original_name?: string;
  first_air_date?: string;
  origin_country?: string[];
}

export interface TrendingShowsResponse {
  results: TrendingShow[];
  page: number;
  total_pages: number;
  total_results: number;
}

export interface TokenRefresh {
  readonly access: string;
  refresh: string;
}

/**
 * @nullable
 */
export type ShowWatchProgressLastWatchedEpisode = TvProgress | null;

export interface PatchedUser {
  readonly id?: number;
  /**
   * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
   * @maxLength 150
   * @pattern ^[\w.@+-]+$
   */
  username?: string;
  /** @maxLength 254 */
  email?: string;
}

/**
 * @nullable
 */
export type PatchedShowWatchProgressLastWatchedEpisode = TvProgress | null;

export interface MovieProgress {
  readonly id: number;
  watched_seconds?: number;
  total_seconds?: number;
}

export interface ShowWatchProgress {
  readonly id: number;
  readonly user: number;
  media_type: MediaTypeEnum;
  /**
   * @minimum -9223372036854776000
   * @maximum 9223372036854776000
   */
  tmdb_id: number;
  /** @maxLength 255 */
  poster_path: string;
  /** @maxLength 255 */
  backdrop_path: string;
  /** @maxLength 255 */
  title: string;
  readonly created_at: string;
  readonly updated_at: string;
  /** @nullable */
  tv_progress: TvProgress[] | null;
  /** @nullable */
  movie_progress: MovieProgress[] | null;
  /** @nullable */
  readonly last_watched_episode: ShowWatchProgressLastWatchedEpisode;
}

export interface PatchedShowWatchProgress {
  readonly id?: number;
  readonly user?: number;
  media_type?: MediaTypeEnum;
  /**
   * @minimum -9223372036854776000
   * @maximum 9223372036854776000
   */
  tmdb_id?: number;
  /** @maxLength 255 */
  poster_path?: string;
  /** @maxLength 255 */
  backdrop_path?: string;
  /** @maxLength 255 */
  title?: string;
  readonly created_at?: string;
  readonly updated_at?: string;
  /** @nullable */
  tv_progress?: TvProgress[] | null;
  /** @nullable */
  movie_progress?: MovieProgress[] | null;
  /** @nullable */
  readonly last_watched_episode?: PatchedShowWatchProgressLastWatchedEpisode;
}

export type MovieDetailSpokenLanguagesItem = { [key: string]: unknown };

export type MovieDetailProductionCountriesItem = { [key: string]: unknown };

export type MovieDetailProductionCompaniesItem = { [key: string]: unknown };

/**
 * @nullable
 */
export type MovieDetailBelongsToCollection = unknown | null;

/**
 * * `tv` - tv
 * `movie` - movie
 */
export enum MediaTypeEnum {
  tv = "tv",
  movie = "movie",
}
export interface Genre {
  id: number;
  name: string;
}

export interface MovieDetail {
  adult: boolean;
  /** @nullable */
  backdrop_path: string | null;
  /** @nullable */
  belongs_to_collection: MovieDetailBelongsToCollection;
  budget: number;
  genres: Genre[];
  /** @nullable */
  homepage: string | null;
  id: number;
  imdb_id: string;
  original_language: string;
  original_title: string;
  overview: string;
  popularity: number;
  /** @nullable */
  poster_path: string | null;
  production_companies: MovieDetailProductionCompaniesItem[];
  production_countries: MovieDetailProductionCountriesItem[];
  release_date: string;
  revenue: number;
  runtime: number;
  spoken_languages: MovieDetailSpokenLanguagesItem[];
  status: string;
  tagline: string;
  title: string;
  video: boolean;
  vote_average: number;
  vote_count: number;
}

export interface EmailTokenObtain {
  email: string;
  password: string;
}
