// @ts-nocheck

/**
 * Auto Generated by orval
 * Do not edit manually.
 * BaseApp Backend API
 * API para el sistema de BaseApp Backend
 */

export interface UserRegistration {
  /**
   * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
   * @maxLength 150
   * @pattern ^[\w.@+-]+$
   */
  username: string;
  /** @maxLength 254 */
  email?: string;
  password: string;
}

export interface User {
  readonly id: number;
  /**
   * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
   * @maxLength 150
   * @pattern ^[\w.@+-]+$
   */
  username: string;
  /** @maxLength 254 */
  email?: string;
}

export interface TrendingShow {
  id: number;
  /** @nullable */
  backdrop_path: string | null;
  /** @nullable */
  poster_path: string | null;
  overview: string;
  media_type: MediaTypeEnum;
  adult: boolean;
  original_language: string;
  genre_ids: number[];
  popularity: number;
  vote_average: number;
  vote_count: number;
  title?: string;
  original_title?: string;
  release_date?: string;
  video?: boolean;
  name?: string;
  original_name?: string;
  first_air_date?: string;
  origin_country?: string[];
}

export interface TrendingShowsResponse {
  results: TrendingShow[];
  page: number;
  total_pages: number;
  total_results: number;
}

export interface TokenRefresh {
  readonly access: string;
  refresh: string;
}

export interface PatchedUser {
  readonly id?: number;
  /**
   * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
   * @maxLength 150
   * @pattern ^[\w.@+-]+$
   */
  username?: string;
  /** @maxLength 254 */
  email?: string;
}

/**
 * * `tv` - tv
 * `movie` - movie
 */
export enum MediaTypeEnum {
  tv = "tv",
  movie = "movie",
}
export interface EmailTokenObtain {
  email: string;
  password: string;
}
